channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.13.7
  - python_abi=3.13
  - readline=8.3
  - setuptools=72.1.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.1.4
      - easydict==1.13
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - insightface==0.7.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - milvus==2.3.5
      - milvus-lite==2.5.1
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - narwhals==2.7.0
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - onnx==1.19.0
      - onnxruntime-gpu==1.23.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - prettytable==3.16.0
      - protobuf==6.32.1
      - psutil==7.1.0
      - pyarrow==21.0.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydeck==0.9.1
      - pymilvus==2.6.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.50.0
      - stringzilla==4.2.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.4
      - toml==0.10.2
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - triton==3.4.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - ultralytics==8.3.206
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0
      - watchdog==6.0.0
      - wcwidth==0.2.14
